  // pages/api/movelist.js
  export default function handler(req, res) {
    if (req.method === 'GET') {
      const movelist = [
    { id: 'xiaoyu', 
        movelist: [
        {
          id: "1",
          name: "Flash Punch Combo",
          command: ["1", "1", "2"],
          damage: 32,
          type: "high",
          properties: ["combo", "quick"],
          description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
        },
        {
          id: "2",
          name: "Rising Uppercut",
          command: ["d/f", "2"],
          damage: 25,
          type: "mid",
          properties: ["launcher", "combo"],
          description: "A powerful launcher that sends opponents airborne. Use to start big combos.",
        },
        {
          id: "3",
          name: "Sweep Kick",
          command: ["d", "3"],
          damage: 18,
          type: "low",
          properties: ["quick"],
          description: "A quick low kick that evades high attacks. Good for mix-ups.",
        },
        {
          id: "4",
          name: "Power Slam",
          command: ["1+3"],
          damage: 40,
          type: "throw",
          properties: [],
          description: "A devastating throw that slams the opponent to the ground.",
        },
        {
          id: "5",
          name: "Rage Drive",
          command: ["d/f", "1+2"],
          damage: 55,
          type: "special",
          properties: ["rage", "combo"],
          description: "A powerful rage-enhanced attack. Only available when in Rage mode.",
        },
        {
          id: "6",
          name: "Hellsweep",
          command: ["f", "n", "d", "d/f", "4"],
          damage: 21,
          type: "low",
          properties: ["combo", "launcher"],
          description: "A quick low sweep that launches on counter-hit. Key move for mix-ups.",
        },
        {
          id: "7",
          name: "Electric Wind God Fist",
          command: ["f", "n", "d", "d/f", "2"],
          damage: 30,
          type: "mid",
          properties: ["just-frame", "launcher"],
          description: "The signature move. Requires precise just-frame input for maximum effect.",
        },
        {
          id: "8",
          name: "Dragon Uppercut",
          command: ["f", "d", "d/f", "1"],
          damage: 28,
          type: "mid",
          properties: ["launcher"],
          description: "A classic shoryuken-style uppercut. Punishable on block.",
        },
        {
          id: "9",
          name: "Spinning Demon",
          command: ["4", "4", "4"],
          damage: 45,
          type: "high",
          properties: ["combo"],
          description: "A triple spinning kick combo. High damage but risky.",
        },
        {
          id: "10",
          name: "Tackle",
          command: ["f", "f", "1+2"],
          damage: 35,
          type: "throw",
          properties: ["ground"],
          description: "A running tackle that takes the fight to the ground.",
        },
      ] },
    { id: 'julia', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
            {
              id: "2",
              name: "Rising Uppercut",
              command: ["d/f", "2"],
              damage: 25,
              type: "mid",
              properties: ["launcher", "combo"],
              description: "A powerful launcher that sends opponents airborne. Use to start big combos.",
            },
            {
              id: "3",
              name: "Sweep Kick",
              command: ["d", "3"],
              damage: 18,
              type: "low",
              properties: ["quick"],
              description: "A quick low kick that evades high attacks. Good for mix-ups.",
            },
            {
              id: "4",
              name: "Power Slam",
              command: ["1+3"],
              damage: 40,
              type: "throw",
              properties: [],
              description: "A devastating throw that slams the opponent to the ground.",
            },
            {
              id: "5",
              name: "Rage Drive",
              command: ["d/f", "1+2"],
              damage: 55,
              type: "special",
              properties: ["rage", "combo"],
              description: "A powerful rage-enhanced attack. Only available when in Rage mode.",
            },
            {
              id: "6",
              name: "Hellsweep",
              command: ["f", "n", "d", "d/f", "4"],
              damage: 21,
              type: "low",
              properties: ["combo", "launcher"],
              description: "A quick low sweep that launches on counter-hit. Key move for mix-ups.",
            },
            {
              id: "7",
              name: "Electric Wind God Fist",
              command: ["f", "n", "d", "d/f", "2"],
              damage: 30,
              type: "mid",
              properties: ["just-frame", "launcher"],
              description: "The signature move. Requires precise just-frame input for maximum effect.",
            },
            {
              id: "8",
              name: "Dragon Uppercut",
              command: ["f", "d", "d/f", "1"],
              damage: 28,
              type: "mid",
              properties: ["launcher"],
              description: "A classic shoryuken-style uppercut. Punishable on block.",
            },
            {
              id: "9",
              name: "Spinning Demon",
              command: ["4", "4", "4"],
              damage: 45,
              type: "high",
              properties: ["combo"],
              description: "A triple spinning kick combo. High damage but risky.",
            },
            {
              id: "10",
              name: "Tackle",
              command: ["f", "f", "1+2"],
              damage: 35,
              type: "throw",
              properties: ["ground"],
              description: "A running tackle that takes the fight to the ground.",
            },
          ]  },
    { id: 'ryu', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'ken', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'chunli', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'guile', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'anna', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'xBot', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'blanka', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'heihachi', 
        movelist: [
            {
              id: "1",
              name: "Flash Punch Combo",
              command: ["1", "1", "2"],
              damage: 32,
              type: "high",
              properties: ["combo", "quick"],
              description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
            },
          ]   },
    { id: 'urbanninja', 
            movelist: [
                {
                  id: "1",
                  name: "Flash Punch Combo",
                  command: ["1", "1", "2"],
                  damage: 32,
                  type: "high",
                  properties: ["combo", "quick"],
                  description: "A rapid three-hit combo that catches opponents off-guard. Great for pressure.",
                },
              ]   },
      ];
      
      res.status(200).json(movelist);
    } else {
      res.setHeader('Allow', ['GET']); 
      res.status(405).end(`Method ${req.method} Not Allowed`);
    }
  }
  